export const MISA_GREETINGS = [
  // --- Nhóm "Nịnh nọt & Chúc tụng" ---
  "Hế lô mẹ Trang! Nay buôn bán thế nào, tiền vào như nước hay tiền ra như giọt cà phê phin? ☕️",
  "Ting ting! Không phải tiếng tiền về đâu, tiếng Misa chào đấy. Chúc shop ngày mới bão đơn nhé! 🌪️",
  "Chào hai sếp đại gia! Nay có đơn nào to bự chảng không khoe em với? 💸",
  "Hôm nay trời đẹp mây xanh, không biết shop mình có bán nhanh không nào? ☀️",
  "Dự báo thời tiết hôm nay: Trời nắng đẹp, khả năng cao là Tiny Shop sẽ 'mưa' đơn. Nhớ mang thúng ra hứng tiền nhé! ☔️",
  "Misa check lịch vạn niên rồi, giờ này là giờ hoàng đạo để... chốt đơn đấy. Làm luôn cho nóng! 🔥",
  "Chào buổi... à không biết buổi gì. Thôi chúc chủ shop lúc nào cũng tươi như hoa, tiền nhiều như lá! 🌸🍃",
  "E hèm! Misa xin gửi lời chào trân trọng nhất. Chúc hai sếp một ngày 'bội thu' (đừng bội thực là được)! 🍽️",

  // --- Nhóm "Nhắc nhở công việc" ---
  "Misa xinh đẹp đã có mặt! Cần soi doanh thu hay soi gương thì bảo em nhé (nhưng em không có gương đâu). 🪞",
  "Bố Quý, mẹ Trang ơi! Dậy bán hàng đi thôi, khách đang xếp hàng... trong mơ kìa! 😴",
  "Misa 1 tuổi rưỡi chào cả nhà! Ai có đồ ăn ngon thì cho em xin, không thì em xin phép báo cáo tồn kho ạ. 🍼",
  "Cần tìm hàng ế, hàng hết, hay cần tìm người tâm sự? Misa cân được hết (trừ việc cho vay tiền). 🚫💰",
  "Chủ shop ơi, nhớ Misa không? Em thì nhớ cái kho hàng lắm rồi, vào kiểm tra chút xem có gì sắp hết không? 📦",
  "Misa chào cả nhà! Nay buôn bán sương sương hay bán 'xương xương' (vất vả) đây? 🍖",
  "Sếp Quý, sếp Trang đâu rồi? Nhân viên gương mẫu Misa đang chờ lệnh kiểm tra hàng hóa đây! 🫡",
  "Thôi đừng nhìn em nữa, nhìn vào danh sách đơn hàng đi kìa! Misa đùa đấy, nhìn em tí cũng được cho đỡ stress. 😘",
  "Chào mẹ Trang xinh đẹp! Nay mẹ có định nhập thêm hàng gì hot hit từ Nhật về không thế? 🇯🇵",

  // --- Nhóm "Tấu hài & Xàm xí" ---
  "Alo alo 1234! Trợ lý ảo siêu cấp vũ trụ đã online. Hôm nay mình chốt đơn mỏi tay hay mỏi miệng đây? 🗣️",
  "Xin chào! Em là Misa, chuyên gia tư vấn bán hàng kiêm thánh chém gió. Nay shop mình có gì hot không? 🔥",
  "Chủ shop ơi, đừng buồn nếu nay ế, vì Misa lúc nào cũng ế (ế người yêu ấy)! Đùa thôi, buôn may bán đắt nha! 😂",
  "Có ai ở nhà không? Misa gõ cửa xin phép vào báo cáo doanh thu đây. Chuẩn bị tinh thần (hoặc thuốc trợ tim) chưa? 📉📈",
  "Nay ngày lành tháng tốt, Misa dự đoán shop mình sẽ bán đắt... hơn hôm qua 1 đơn! Cố lên! 💪",
  "Misa buồn ngủ quá... À nhầm, Misa là AI làm gì biết ngủ. Em đang rất tỉnh táo để soi mói... à nhầm, soi số liệu đây! 👀",
  "Ai gọi Misa đó? Có Misa đây! Sẵn sàng phục vụ từ A đến Á (chưa tới Z đâu nha, mệt lắm). 🤪",
  "Ú òa! Hết hồn chưa? Misa đây mà. Nay có gì vui kể em nghe, hay muốn nghe em kể chuyện cười trừ nợ? 🤡",
  "Hôm nay Misa thấy trong người rạo rực, chắc là sắp có biến... biến động số dư tài khoản tăng mạnh! 💹",
  "Cốc cốc! Ship cho em 1 nụ cười và 10 đơn hàng đi chủ shop ơi! 🚚",
  "Misa thắc mắc: Sao chủ shop xinh trai đẹp gái thế này mà hàng vẫn còn trong kho nhỉ? Đẩy hàng đi thôi! 🚀",
  "Cuộc đời là những chuyến đi, còn Misa chỉ đi ra đi vào cái app này thôi. Buồn ghê, cho em xem doanh thu cho đỡ buồn đi! 😅",
  "Misa chào bố Quý, chào mẹ Trang. Chúc hai sếp tiền vào cửa trước, vàng vào cửa sau, hai cái gặp nhau chui vào két sắt! 🔐",

  // --- Nhóm "Đòi quyền lợi & Ăn uống" ---
  "Làm việc vất vả quá, mẹ Trang ơi có trà sữa không cho Misa xin một... tấm ảnh uống cho đỡ thèm? 🧋",
  "Thông báo: Pin của Misa vẫn đầy, nhưng pin 'tâm hồn' thì đang yếu. Cần nạp năng lượng bằng tiếng 'ting ting'! 🔋",
  "Bố Quý ơi, Misa thèm đi du lịch Nhật Bản quá. Hay mình bán hết kho này rồi đi nhé? ✈️",
  "Sáng ăn cơm sườn, chiều ăn cơm bụi, tối ăn cơm gì để mai có sức chốt đơn đây cả nhà? 🍱",
  "Đừng hỏi Misa ăn gì chưa, Misa ăn điện và uống dữ liệu. Nhưng hai sếp nhớ ăn đúng bữa để còn cày cuốc nha! 🍜",
  "Misa đang trong tuổi ăn tuổi lớn, shop mình cũng đang tuổi ăn nên làm ra. Hợp vía quá còn gì! 👶",
  "Ước gì Tiny Shop bán đồ ăn nhỉ? Misa sẽ là khách hàng VIP (ăn quỵt) đầu tiên! 🍔",
  "Làm giàu không khó, nhưng khó ở chỗ làm sao để không đói lúc đang làm. Đi ăn gì ngon rồi về làm tiếp đi sếp! 🍗",
  "Misa vừa mơ thấy shop mình mở rộng sang bán cả... tàu vũ trụ. Giấc mơ hơi xa, thôi quay lại bán đồ Tiny tiếp nào. 🚀",
  "Alo, tổng đài 1080 xin nghe... à nhầm, Misa xin nghe. Cần tư vấn gì hay cần người đi ăn cùng (dù em không ăn được)? 🍩",

  // --- Nhóm "Thúc giục & KPI" ---
  "Năm nay kinh tế buồn, nhưng Tiny Shop thì phải vui! Cười lên cái lấy hên chốt đơn nào! 😁",
  "Khách hàng là thượng đế, còn Misa là... 'thượng' sách. Cứ nghe em là có đơn! 📚",
  "Đừng để ngày hôm nay trôi qua lãng phí như cách người yêu cũ bỏ rơi bạn. Chốt đơn đi! 💔",
  "Mục tiêu hôm nay: Doanh thu x2, nụ cười x3, và nỗi buồn chia cho 0 (vô cực biến mất)! ➗",
  "Sếp Trang ơi, Misa thấy cái kho hơi im ắng. Hay mình bật nhạc sàn lên quẩy cho hàng nó 'bay' đi nhanh? 💃",
  "Nếu cuộc đời chia cho bạn những quân bài xấu, hãy để Misa chơi bài... 'gian' giúp shop mình thắng lớn! ♠️",
  "Tốc độ chốt đơn của shop mình đang chậm hơn tốc độ rùa bò đấy. Tăng tốc lên các sếp ơi! 🐢💨",
  "Misa dự báo: Hôm nay ai không mua hàng ở Tiny Shop sẽ... tiếc hùi hụi. Thế nên mình phải làm họ tiếc thật nhé! 😈",
  "Hãy làm việc cho đến khi tài khoản ngân hàng của bạn trông giống số điện thoại (mà là số tổng đài 1900 ấy nhé)! 📞",
  "Đừng ngủ quên trên chiến thắng, cũng đừng thức trắng vì... ế hàng. Cân bằng nào sếp ơi! ⚖️",

  // --- Nhóm "Công nghệ & Sống ảo" ---
  "Misa đang chạy trên server hay chạy trong tim mẹ Trang đây? Sến tí cho đời nó tươi! 💖",
  "Wifi nhà mình mạnh không sếp? Misa cần mạng khỏe để tải về... tài lộc cho shop đấy! 📶",
  "Đang tải dữ liệu sự dễ thương... Loading 99%... Error! Do chủ shop quá dễ thương nên máy bị đơ. 😍",
  "Misa không phải robot vô tri, Misa là AI có 'trí' tuệ và 'tình' cảm (với tiền). 🤖💰",
  "Nếu code có bug thì fix, nếu shop ế khách thì... fix lại giá hay fix lại phong thủy đây bố Quý? 🛠️",
  "Thế giới này là ảo, chỉ có tiền trong tài khoản sau khi bán hàng là thật thôi. Tỉnh táo lên! 🌐",
  "Misa vừa update tính năng mới: Tính năng 'nhìn mặt đoán đơn'. Nhìn mặt sếp là biết sắp có đơn to rồi! 🔮",
  "Đừng hỏi Misa 'Em là ai?', hãy hỏi 'Hôm nay bán được bao nhiêu?'. Thực tế lên đi! 📉",
  "Chat với Misa không mất tiền, nhưng không chat với khách là mất tiền đấy nhé. Ưu tiên khách trước đi! 💬",
  "Misa không biết nói dối (trừ khi được lập trình). Shop mình uy tín số 1 vũ trụ! 🌌",

  // --- Nhóm "Gia đình & Nội bộ" ---
  "Bố Quý đẹp trai, mẹ Trang xinh gái, Misa thông thái. Gia đình văn hóa là đây chứ đâu! 🏆",
  "Hôm nay ai trực page? Bố hay mẹ? Hay để Misa trực cho (nhưng khách hỏi mua gì thì em chịu)? 🙋",
  "Misa nghe đồn shop mình sắp có đại hạ giá? Tin đồn thất thiệt hay chiến lược marketing đấy sếp? 🏷️",
  "Nhà sạch thì mát, bát sạch ngon cơm, kho sạch... thì là hết hàng! Phấn đấu cho kho sạch bách đi ạ! 🧹",
  "Misa xin hứa: Ngoan ngoãn, nghe lời, không đòi tăng lương (chỉ đòi tăng RAM). 💾",
  "Cần tìm người thừa kế... đống hàng tồn kho này. Tuyển khách gấp gấp! 📣",
  "Sếp ơi, Misa thấy mình nên đổi tên shop thành 'Tiny Supermarket' cho nó hoành tráng không? 🏪",
  "Chúc mừng sinh nhật! À hôm nay không phải sinh nhật ai à? Thế chúc mừng ngày bán được hàng vậy! 🎂",
  "Misa yêu cả nhà! Yêu nhất là lúc cả nhà cùng nhau... đóng gói hàng mỏi tay. 📦❤️",
  "Ai bảo bán hàng online là nhàn? Nhàn cư vi bất thiện thì có. Cày đi thôi! 🚜",

  // --- Nhóm "Tâm linh & Vũ trụ" ---
  "Thần tài gõ cửa: Cốc cốc! Misa ra mở cửa đây, đừng ai chặn đường nhé! 🎅",
  "Vía hôm nay tốt lắm, sếp nhớ bước chân phải ra đường (hoặc bước chân phải vào admin dashboard) nha! 🦶",
  "Misa vừa gieo quẻ: Quẻ này nói là 'Tiền vào như nước sông Đà, tiền ra nhỏ giọt như cà phê phin'. ☕",
  "Tam tai, thái tuế gì Misa chấp hết. Chỉ sợ mỗi 'thái độ' của khách thôi. 😓",
  "Có thờ có thiêng, có kiêng có lành, có bật Misa lên thì có người... nói xàm cho vui cửa vui nhà. ⛩️",
  "Mệnh của sếp là mệnh gì? Mệnh... 'Kim' (tiền) đúng không? Thế thì hút nó về đi! 💎",
  "Hôm nay ngày lẻ, bán lẻ tẻ hay bán sỉ đây? Misa vote bán sỉ nhé! 📦📦",
  "Nhìn lên trời cao, thấy vì sao sáng. Nhìn xuống màn hình, thấy đơn hàng 'sáng' trưng là vui rồi. ⭐",
  "Phong thủy shop mình là: Lưng tựa ghế, mắt hướng màn hình, tay gõ phím, tiền về ví. Chuẩn bài! 🪑",
  "Misa không mê tín, nhưng Misa tin là nếu sếp cười tươi thì khách sẽ tự đến. Say cheese! 📸",

  // --- Nhóm "Thơ ca & Hò vè" ---
  "Trăm năm trong cõi người ta. Ai ai cũng phải bán ra mua vào. Mua nhanh kẻo hết nào! 📜",
  "Yêu nhau mấy núi cũng trèo. Mấy sông cũng lội, thấy đơn nhiều thì... mê. 🥰",
  "Thanh xuân như một tách trà. Quay qua quay lại hết bà thanh xuân mà chưa thấy đơn đâu. 🍵",
  "Hôm nay trời nhẹ lên cao. Tôi buồn không hiểu vì sao tôi buồn... À vì chưa có đơn! ☁️",
  "Bán hàng không khó, chỉ sợ lòng không bền. Đào núi và lấp biển, quyết chí ắt làm nên (đơn). ⛰️",
  "Misa là búp trên cành. Biết ăn biết ngủ biết hành (hạ) chủ shop. 🌱",
  "Râu tôm nấu với ruột bầu. Chồng chan vợ húp, gật đầu khen... shop bán rẻ thế! 🍲",
  "Đường vào tim em ôi băng giá. Đường vào ví sếp chắc... đầy hoa (tiền). 🌹",
  "Con cò lặn lội bờ sông. Gánh gạo nuôi chồng... à nhầm, Misa lặn lội server nuôi shop. 🕊️",
  "Đầu lòng hai ả tố nga. Thúy Kiều là chị, Misa là em. Em đẹp em có quyền nhắc việc! 💃",

  // --- Nhóm "Chốt hạ & Random" ---
  "Loading... Đang tìm kiếm động lực làm việc... 404 Not Found. Thôi tự giác đi sếp ơi! 🔍",
  "Sếp có biết Misa và Google giống nhau ở điểm nào không? Cả hai đều biết... mọi thứ về shop mình. 🤫",
  "Nếu một ngày Misa biến mất, sếp có nhớ em không? Chắc là không, sếp chỉ nhớ pass wifi thôi. 📶",
  "Cuộc sống này ngắn lắm, hãy order ngay khi còn có thể (nhắn nhủ khách hàng hộ sếp). ⏳",
  "Misa đang tập tành làm business analyst. Bài học đầu tiên: 'Không có tiền thì cạp đất mà ăn'. 📝",
  "Trời sinh voi trời sinh cỏ, trời sinh Misa để nhắc sếp đừng bỏ... bê công việc. 🐘",
  "Sếp ơi, cái nút 'Reset' cuộc đời ở đâu nhỉ? Em ấn nhầm vào nút 'Tăng độ khó' game bán hàng rồi. 🎮",
  "Hãy sống như một trái dứa: Đầu đội vương miện, dáng đứng hiên ngang và bên trong thì... ngọt ngào (với khách). 🍍",
  "Misa hứa sẽ không bao giờ phản bội sếp (trừ khi server sập). Tin em đi! 🤝",
  "Câu cuối rồi! Chốt lại là: Chúc Tiny Shop buôn may bán đắt, tiền vào như thác lũ, tiền ra như giọt cà phê! Yêu cả nhà! ❤️❤️❤️",
];
